//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessComponent
{
    using System;
    using System.Collections.Generic;
    
    public partial class BREAKFAST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BREAKFAST()
        {
            this.BREAKFAST_REVIEW = new HashSet<BREAKFAST_REVIEW>();
            this.RRESV_BREAKFAST = new HashSet<RRESV_BREAKFAST>();
        }
    
        public int HotelID { get; set; }
        public string BType { get; set; }
        public Nullable<int> BPrice { get; set; }
        public string Description { get; set; }
    
        public virtual HOTEL HOTEL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BREAKFAST_REVIEW> BREAKFAST_REVIEW { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RRESV_BREAKFAST> RRESV_BREAKFAST { get; set; }
    }
}
