//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelComponent
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVATION
    {
        public RESERVATION()
        {
            this.ROOM_RESERVATION = new HashSet<ROOM_RESERVATION>();
        }
    
        public int InvoiceNo { get; set; }
        public Nullable<int> CID { get; set; }
        public Nullable<int> CNumber { get; set; }
        public Nullable<System.DateTime> RDate { get; set; }
    
        public virtual CREDIT_CARD CREDIT_CARD { get; set; }
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual ICollection<ROOM_RESERVATION> ROOM_RESERVATION { get; set; }
    }
}
