//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelComponent
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICE
    {
        public SERVICE()
        {
            this.RRESV_SERVICE = new HashSet<RRESV_SERVICE>();
            this.SERVICE_REVIEW = new HashSet<SERVICE_REVIEW>();
        }
    
        public int HotelID { get; set; }
        public string SType { get; set; }
        public Nullable<int> SPrice { get; set; }
    
        public virtual HOTEL HOTEL { get; set; }
        public virtual ICollection<RRESV_SERVICE> RRESV_SERVICE { get; set; }
        public virtual ICollection<SERVICE_REVIEW> SERVICE_REVIEW { get; set; }
    }
}
